name: 'App Deploy'

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: false
        default: 'Deploy Static Web App'
      app_location:
        type: string
        required: false
        default: app
      api_location:
        type: string
        required: false
        default: api
      output_location:
        type: string
        required: false
        default: wwwroot
    secrets:
      gh_token:
        required: true
      aswa_token:
        required: true

jobs:
  deploy:
    name: ${{ inputs.job_name }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        submodules: true

    # - name: Set up .NET 6 SDK
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: '6.x'

    # - name: Restore NuGet packages
    #   shell: bash
    #   run: |
    #     dotnet restore .

    # - name: Build solution
    #   shell: bash
    #   run: |
    #     dotnet build . -c Release

    # - name: Publish App
    #   shell: bash
    #   run: |
    #     pushd ${{ inputs.app_location }}
    #     dotnet publish . -c Release -o published
    #     popd

    # - name: Publish API
    #   shell: bash
    #   run: |
    #     pushd ${{ inputs.api_location }}
    #     dotnet publish . -c Release -o published
    #     popd

    - name: Deploy Static Web App 
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.aswa_token }}
        repo_token: ${{ secrets.gh_token }} # Used for Github integrations (i.e. PR comments)
        action: upload
        # skip_app_build: true
        # skip_api_build: true
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: ${{ inputs.app_location }} # App source code path
        api_location: ${{ inputs.api_location }} # Api source code path - optional
        output_location: ${{ inputs.output_location }} # Built app content directory - optional
        ###### End of Repository/Build Configurations ######
